name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true
        cache: true

    - name: Generate Coverage Report
      run: go test -coverprofile=coverage.out ./...

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        fail_ci_if_error: true 